package vista;

/**
 *
 * @author fvasq
 */
public class VistaMenu extends javax.swing.JFrame {
   
    

    /**
     * Creates new form Menu
     */
    public VistaMenu() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listaOrdenes = new javax.swing.JButton();
        nuevaOrden = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/238.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        listaOrdenes.setText("Lista de ordenes");
        getContentPane().add(listaOrdenes);
        listaOrdenes.setBounds(250, 320, 137, 39);

        nuevaOrden.setText("Nueva orden");
        nuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(nuevaOrden);
        nuevaOrden.setBounds(30, 320, 115, 39);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_logotipo_proyecto_de_complejidad.png"))); // NOI18N
        Logo.setToolTipText("");
        getContentPane().add(Logo);
        Logo.setBounds(140, 10, 170, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/450.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 420, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton listaOrdenes;
    public javax.swing.JButton nuevaOrden;
    // End of variables declaration//GEN-END:variables
    
    
    
  
}



